/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void serial_list_click1(GDropList source, GEvent event) { //_CODE_:serial_list:915007:
  println("serial_list - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:serial_list:915007:

public void serial_button_click1(GButton source, GEvent event) { //_CODE_:serial_button:757048:
  println("serial_button - GButton >> GEvent." + event + " @ " + millis());
  connessioneSeriale();  //call connection to serial port function
} //_CODE_:serial_button:757048:

public void saveData_button_click1(GButton source, GEvent event) { //_CODE_:serial_button:757048:
  println("saveData_button - GButton >> GEvent." + event + " @ " + millis());
  salvaDato(); //save data in a selected file
} //_CODE_:serial_button:757048:

public void selFile_button_click1(GButton source, GEvent event) { //_CODE_:serial_button:757048:
  println("selFile_button - GButton >> GEvent." + event + " @ " + millis());
  selezionaFile();  //select a file in a selected directory //<>//
} //_CODE_:serial_button:757048:

public void sensorFileMAP_button_click1(GButton source, GEvent event) { //_CODE_:serial_button:757048:
  println("sensorFileMAP_button - GButton >> GEvent." + event + " @ " + millis());
  sciegliFile();  //select a file in a selected directory
} //_CODE_:serial_button:757048:

public void sensorActivation_button_click1(GButton source, GEvent event) { //_CODE_:serial_button:757048:
  println("sensorActivation_button - GButton >> GEvent." + event + " @ " + millis());
  onOff();  //control the activation of hall sensor
} //_CODE_:serial_button:757048:

// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  
  //serial menu setup
  
  //------------------------global set
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Magic Software");
  //---------------------------------
  
  //-----------------label set
  serial_label = new GLabel(this, 18, 19, 223, 91);
  serial_label.setTextAlign(GAlign.LEFT, GAlign.TOP);
  serial_label.setLocalColorScheme(GCScheme.YELLOW_SCHEME);
  serial_label.setOpaque(true);
  serial_label.setText("     Serial ports:");
  //----------------------------------------
  
  //------------ droplist set
  serial_list = new GDropList(this, 124, 24, 116, 80, 3, 10);
  serial_list.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  serial_list.setOpaque(true);
  serial_list.setItems(loadStrings("list_915007"), 0);
  serial_list.addEventHandler(this, "serial_list_click1");
  //--------------------
  
  //-------------------button set
  serial_button = new GButton(this, 24, 51, 86, 30);
  serial_button.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  serial_button.setOpaque(true);
  serial_button.setText("Connect");
  serial_button.addEventHandler(this, "serial_button_click1");
  //--------------------
  
  //end serial menu stup
  
  
  //save file setup
  
  //--------------------data file location
  dataLocation_label = new GLabel(this, 254, 19, 270, 61);
  dataLocation_label.setTextAlign(GAlign.LEFT, GAlign.BOTTOM);
  dataLocation_label.setText("Location:");
  dataLocation_label.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  dataLocation_label.setOpaque(true);
  //---------------------------------------------
  
  //----------------selection file button
  selFile_button = new GButton(this, 262, 22, 130, 26);
  selFile_button.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  selFile_button.setOpaque(true);
  selFile_button.setText("Select File");
  selFile_button.addEventHandler(this, "selFile_button_click1");
  //--------------------------------------------------------
  
  //----------save data button 
  saveData_button = new GButton(this, 422, 22, 80, 26);
  saveData_button.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  saveData_button.setOpaque(true);
  saveData_button.setText("Save");
  saveData_button.addEventHandler(this, "saveData_button_click1");
  //---------------------------------------------------------------
  
  //end save file setup
  
  //sensor controlling 
  
  //---------------label setup
  sensor_controll_label = new GLabel(this, 18, 130, 223, 91);
  sensor_controll_label.setTextAlign(GAlign.LEFT, GAlign.TOP);
  sensor_controll_label.setLocalColorScheme(GCScheme.YELLOW_SCHEME);
  sensor_controll_label.setOpaque(true);
  sensor_controll_label.setText("   Sensor controller:");
  //-------------------------------------
  
  //-------------------button selFile setup
  sensorFileMAP_button = new GButton(this, 30, 162, 86, 30);
  sensorFileMAP_button.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  sensorFileMAP_button.setOpaque(true);
  sensorFileMAP_button.setText("Sel Map");
  sensorFileMAP_button.addEventHandler(this, "sensorFileMAP_button_click1");
  //-------------------------
  
  //-------------------button OnOff setup
  sensorActivation_button = new GButton(this, 140, 162, 86, 30);
  sensorActivation_button.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  sensorActivation_button.setOpaque(true);
  sensorActivation_button.setText("On - Off");
  sensorActivation_button.addEventHandler(this, "sensorActivation_button_click1");
  //-------------------------
  
  //end sensor controlling 
  
  //display value 
  
  //------------value label setup 
  display1 = new GLabel(this, 261, 130, 223, 60);
  display1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  display1.setText("VALUE");
  display1.setOpaque(true);
  
  
}

// Variable declarations 
// autogenerated do not edit

//creazione delle etichette
GLabel dataLocation_label;
GLabel serial_label;
GLabel display1;
GLabel sensor_controll_label;

//creazione droplist
GDropList serial_list;

//creazione dei bottoni
GButton serial_button;
GButton selFile_button;
GButton saveData_button;
GButton sensorFileMAP_button;
GButton sensorActivation_button;
