/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void dropList1_click1(GDropList source, GEvent event) { //_CODE_:dropList1:650212:
  println("dropList1 - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:dropList1:650212:

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:999297:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
  if(myPort==null){
    String comDaUsare= dropList1.getSelectedText();
    myPort = new Serial(this, comDaUsare, 9600);
    button1.setText("DISCONNECT");
   }else{
     button1.setText("CONNECT");
     myPort.stop();
     myPort=null;
   }

} //_CODE_:button1:999297:

public void custom_slider1_change1(GCustomSlider source, GEvent event) { //_CODE_:red_color:496114:
  //println("red_color - GCustomSlider >> GEvent." + event + " @ " + millis());
  numbers[0] = source.getValueI();
  //println(numbers[0]);
} //_CODE_:red_color:496114:

public void custom_slider1_change2(GCustomSlider source, GEvent event) { //_CODE_:green_color:208960:
  //println("green_color - GCustomSlider >> GEvent." + event + " @ " + millis());
  numbers[1] = source.getValueI();
  //println(numbers[1]);
} //_CODE_:green_color:208960:

public void custom_slider1_change3(GCustomSlider source, GEvent event) { //_CODE_:blue_color:849542:
  //println("blue_color - GCustomSlider >> GEvent." + event + " @ " + millis());
  numbers[2] = source.getValueI();
  //println(numbers[2]);
} //_CODE_:blue_color:849542:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  temperatura = new GLabel(this, 7, 91, 250, 45);
  temperatura.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  temperatura.setText("Temperature");
  temperatura.setOpaque(true);
  dropList1 = new GDropList(this, 153, 22, 150, 180, 3, 10);
  dropList1.setItems(loadStrings("list_650212"), 0);
  dropList1.addEventHandler(this, "dropList1_click1");
  label1 = new GLabel(this, 2, 22, 150, 45);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Sel COM:");
  label1.setTextBold();
  label1.setOpaque(true);
  button1 = new GButton(this, 304, 22, 150, 45);
  button1.setText("CONNETTI");
  button1.addEventHandler(this, "button1_click1");
  humidity = new GLabel(this, 8, 140, 250, 45);
  humidity.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  humidity.setText("Humidity");
  humidity.setOpaque(true);
  heat_index = new GLabel(this, 7, 189, 250, 45);
  heat_index.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  heat_index.setText("Heat Index");
  heat_index.setOpaque(true);
  red_color = new GCustomSlider(this, 102, 259, 500, 45, "grey_blue");
  red_color.setShowValue(true);
  red_color.setLimits(0, 0, 255);
  red_color.setNumberFormat(G4P.INTEGER, 0);
  red_color.setOpaque(true);
  red_color.addEventHandler(this, "custom_slider1_change1");
  green_color = new GCustomSlider(this, 102, 310, 500, 45, "grey_blue");
  green_color.setShowValue(true);
  green_color.setLimits(0, 0, 255);
  green_color.setNumberFormat(G4P.INTEGER, 0);
  green_color.setOpaque(true);
  green_color.addEventHandler(this, "custom_slider1_change2");
  blue_color = new GCustomSlider(this, 103, 363, 500, 45, "grey_blue");
  blue_color.setShowValue(true);
  blue_color.setLimits(0, 0, 255);
  blue_color.setNumberFormat(G4P.INTEGER, 0);
  blue_color.setOpaque(true);
  blue_color.addEventHandler(this, "custom_slider1_change3");
  label2 = new GLabel(this, 0, 259, 100, 45);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("RED");
  label2.setOpaque(true);
  label3 = new GLabel(this, 0, 308, 100, 45);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("BLUE");
  label3.setOpaque(true);
  label4 = new GLabel(this, -1, 360, 100, 45);
  label4.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label4.setText("GREEN");
  label4.setOpaque(true);
}

// Variable declarations 
// autogenerated do not edit
GLabel temperatura; 
GDropList dropList1; 
GLabel label1; 
GButton button1; 
GLabel humidity; 
GLabel heat_index; 
GCustomSlider red_color; 
GCustomSlider green_color; 
GCustomSlider blue_color; 
GLabel label2; 
GLabel label3; 
GLabel label4; 
