/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void dropList1_click1(GDropList source, GEvent event) { //_CODE_:dropList1:650212:
  println("dropList1 - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:dropList1:650212:

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:999297:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
  if(myPort==null){
    String comDaUsare= dropList1.getSelectedText();
    myPort = new Serial(this, comDaUsare, 9600);
    button1.setText("DISCONNECT");
   }else{
     button1.setText("CONNECT");
     myPort.stop();
     myPort=null;
   }
   
} //_CODE_:button1:999297:

public void rele1_click1(GButton source, GEvent event) { //_CODE_:rele1:551817:
  println("rele1 - GButton >> GEvent." + event + " @ " + millis());
  controllo_rele1 = !controllo_rele1;    
  if(controllo_rele1 == true){
      myPort.write('a');
  }else if(controllo_rele1 == false){
    myPort.write('A');
  }
} //_CODE_:rele1:551817:

public void rele2_click1(GButton source, GEvent event) { //_CODE_:rele2:706215:
  println("rele2 - GButton >> GEvent." + event + " @ " + millis());
  controllo_rele2 = !controllo_rele2;    
  if(controllo_rele2 == true){
      myPort.write('b');
  }else if(controllo_rele2 == false){
    myPort.write('B');
  }
} //_CODE_:rele2:706215:

public void rele3_click1(GButton source, GEvent event) { //_CODE_:rele3:528005:
  println("rele3 - GButton >> GEvent." + event + " @ " + millis());
  controllo_rele3 = !controllo_rele3;    
  if(controllo_rele3 == true){
      myPort.write('c');
  }else if(controllo_rele3 == false){
    myPort.write('C');
  }
} //_CODE_:rele3:528005:

public void rele4_click1(GButton source, GEvent event) { //_CODE_:rele4:778201:
  println("rele4 - GButton >> GEvent." + event + " @ " + millis());
  controllo_rele4 = !controllo_rele4;    
  if(controllo_rele4 == true){
      myPort.write('d');
  }else if(controllo_rele4 == false){
    myPort.write('D');
  }
} //_CODE_:rele4:778201:

public void rele5_click1(GButton source, GEvent event) { //_CODE_:rele5:573313:
  println("rele5 - GButton >> GEvent." + event + " @ " + millis());
  controllo_rele5 = !controllo_rele5;    
  if(controllo_rele5 == true){
      myPort.write('e');
  }else if(controllo_rele5 == false){
    myPort.write('E');
  }
} //_CODE_:rele5:573313:

public void rele6_click1(GButton source, GEvent event) { //_CODE_:rele6:911754:
  println("rele6 - GButton >> GEvent." + event + " @ " + millis());
  controllo_rele6 = !controllo_rele6;    
  if(controllo_rele6 == true){
      myPort.write('f');
  }else if(controllo_rele6 == false){
    myPort.write('F');
  }
} //_CODE_:rele6:911754:

public void rele7_click1(GButton source, GEvent event) { //_CODE_:rele7:931766:
  println("rele7 - GButton >> GEvent." + event + " @ " + millis());
  controllo_rele7 = !controllo_rele7;   
  if(controllo_rele7 == true){
      myPort.write('g');
  }else if(controllo_rele7 == false){
    myPort.write('G');
  }
} //_CODE_:rele7:931766:

public void rele8_click1(GButton source, GEvent event) { //_CODE_:rele8:710356:
  println("rele8 - GButton >> GEvent." + event + " @ " + millis());
  controllo_rele8 = !controllo_rele8;  
  if(controllo_rele8 == true){
        myPort.write('h');
  }else if(controllo_rele8 == false){
    myPort.write('H');
  }
} //_CODE_:rele8:710356:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  temperatura = new GLabel(this, 7, 91, 250, 45);
  temperatura.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  temperatura.setText("Temperature");
  temperatura.setOpaque(true);
  dropList1 = new GDropList(this, 153, 22, 150, 180, 3, 10);
  dropList1.setItems(loadStrings("list_650212"), 0);
  dropList1.addEventHandler(this, "dropList1_click1");
  label1 = new GLabel(this, 2, 22, 150, 45);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Sel COM:");
  label1.setTextBold();
  label1.setOpaque(true);
  button1 = new GButton(this, 304, 22, 150, 45);
  button1.setText("CONNETTI");
  button1.addEventHandler(this, "button1_click1");
  humidity = new GLabel(this, 8, 140, 250, 45);
  humidity.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  humidity.setText("Humidity");
  humidity.setOpaque(true);
  movimento = new GLabel(this, 9, 257, 250, 45);
  movimento.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  movimento.setText("Movimento");
  movimento.setOpaque(true);
  soil_humidity = new GLabel(this, 9, 201, 250, 45);
  soil_humidity.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  soil_humidity.setText("Soil Humidity");
  soil_humidity.setOpaque(true);
  rele1 = new GButton(this, 11, 335, 80, 30);
  rele1.setText("Rele 1");
  rele1.addEventHandler(this, "rele1_click1");
  rele2 = new GButton(this, 111, 336, 80, 30);
  rele2.setText("Rele 2");
  rele2.addEventHandler(this, "rele2_click1");
  rele3 = new GButton(this, 206, 335, 80, 30);
  rele3.setText("Rele 3");
  rele3.addEventHandler(this, "rele3_click1");
  rele4 = new GButton(this, 306, 336, 80, 30);
  rele4.setText("Rele 4");
  rele4.addEventHandler(this, "rele4_click1");
  rele5 = new GButton(this, 5, 385, 80, 30);
  rele5.setText("Rele 5");
  rele5.addEventHandler(this, "rele5_click1");
  rele6 = new GButton(this, 112, 386, 80, 30);
  rele6.setText("Rele 6");
  rele6.addEventHandler(this, "rele6_click1");
  rele7 = new GButton(this, 210, 384, 80, 30);
  rele7.setText("Rele 7");
  rele7.addEventHandler(this, "rele7_click1");
  rele8 = new GButton(this, 308, 381, 80, 30);
  rele8.setText("Rele 8");
  rele8.addEventHandler(this, "rele8_click1");
}

// Variable declarations 
// autogenerated do not edit
GLabel temperatura; 
GDropList dropList1; 
GLabel label1; 
GButton button1; 
GLabel humidity; 
GLabel movimento; 
GLabel soil_humidity; 
GButton rele1; 
GButton rele2; 
GButton rele3; 
GButton rele4; 
GButton rele5; 
GButton rele6; 
GButton rele7; 
GButton rele8; 
