/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void serial_list_click1(GDropList source, GEvent event) { //_CODE_:serial_list:371820:
  println("serial_list - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:serial_list:371820:

public void serial_button_click1(GButton source, GEvent event) { //_CODE_:serial_button:402234:
  println("serial_button - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:serial_button:402234:

public void fileSelection_click1(GButton source, GEvent event) { //_CODE_:fileSelection:865783:
  println("fileSelection - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:fileSelection:865783:

public void saveButton_click1(GButton source, GEvent event) { //_CODE_:saveButton:580249:
  println("saveButton - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:saveButton:580249:

public void on_off_button_click1(GButton source, GEvent event) { //_CODE_:on_off_button:556459:
  println("on_off_button - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:on_off_button:556459:

public void fileMap_button_click1(GButton source, GEvent event) { //_CODE_:fileMap_button:561195:
  println("fileMap_button - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:fileMap_button:561195:

public void controllValue_change1(GTextField source, GEvent event) { //_CODE_:controllValue:215607:
  println("textfield2 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:controllValue:215607:

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:318226:
  appc.background(230);
} //_CODE_:window1:318226:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  serial_label = new GLabel(this, 20, 20, 140, 80);
  serial_label.setTextAlign(GAlign.LEFT, GAlign.TOP);
  serial_label.setText("Serial port");
  serial_label.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  serial_label.setOpaque(true);
  serial_list = new GDropList(this, 110, 20, 50, 80, 3, 10);
  serial_list.setItems(loadStrings("list_371820"), 0);
  serial_list.addEventHandler(this, "serial_list_click1");
  serial_button = new GButton(this, 24, 53, 70, 30);
  serial_button.setText("CONNECT");
  serial_button.addEventHandler(this, "serial_button_click1");
  valueGauss = new GLabel(this, 180, 20, 140, 80);
  valueGauss.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  valueGauss.setText("Gauss");
  valueGauss.setOpaque(true);
  dataLocation = new GLabel(this, 340, 20, 240, 30);
  dataLocation.setText("Location --> ");
  dataLocation.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  dataLocation.setOpaque(true);
  fileSelection = new GButton(this, 370, 70, 80, 30);
  fileSelection.setText("Sel file");
  fileSelection.addEventHandler(this, "fileSelection_click1");
  saveButton = new GButton(this, 460, 70, 80, 30);
  saveButton.setText("Save");
  saveButton.addEventHandler(this, "saveButton_click1");
  sensor_controller = new GLabel(this, 20, 120, 300, 50);
  sensor_controller.setText("Sensor Controller");
  sensor_controller.setOpaque(true);
  on_off_button = new GButton(this, 140, 130, 80, 30);
  on_off_button.setText("On - Off");
  on_off_button.addEventHandler(this, "on_off_button_click1");
  fileMap_button = new GButton(this, 230, 130, 80, 30);
  fileMap_button.setText("File Map");
  fileMap_button.addEventHandler(this, "fileMap_button_click1");
  soglia_label = new GLabel(this, 340, 120, 90, 50);
  soglia_label.setText("Controll Value:");
  soglia_label.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  soglia_label.setOpaque(true);
  controllValue = new GTextField(this, 430, 120, 90, 50, G4P.SCROLLBARS_NONE);
  controllValue.setText("Insert Value");
  controllValue.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  controllValue.setOpaque(true);
  controllValue.addEventHandler(this, "controllValue_change1");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 240, 120, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GLabel serial_label; 
GDropList serial_list; 
GButton serial_button; 
GLabel valueGauss; 
GLabel dataLocation; 
GButton fileSelection; 
GButton saveButton; 
GLabel sensor_controller; 
GButton on_off_button; 
GButton fileMap_button; 
GLabel soglia_label; 
GTextField controllValue; 
GWindow window1;
